# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^control-plane/src/.*\.py$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file=.yamllint]
        files: \.yml$

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        additional_dependencies: ["isort==5.13.2"]
        files: ^control-plane/src/.*\.py$

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        additional_dependencies: ["pylint==3.3.1"]
        files: ^control-plane/src/.*\.py$

      - id: bandit
        name: bandit
        entry: bandit -q -r src/
        language: python
        additional_dependencies: ["bandit==1.7.10"]
        files: ^control-plane/src/.*\.py$

      # Rust checks
      - id: cargo-fmt
        name: Rust formatting
        entry: bash -c 'cd capture-engine && cargo fmt --all -- --check'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: Rust linting
        entry: bash -c 'cd capture-engine && cargo clippy -- -D warnings'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-audit
        name: Rust security audit
        entry: bash -c 'cd capture-engine && cargo audit'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: Rust tests
        entry: bash -c 'cd capture-engine && cargo test'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-deny
        name: Rust dependency check
        entry: bash -c 'cd capture-engine && cargo deny check'
        language: system
        types: [rust]
        pass_filenames: false
