---
name: CI

on:
    workflow_call:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    control-plane-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r control-plane/requirements.txt

            - name: Run isort
              run: |
                isort control-plane/src/ control-plane/tests/ --check-only --diff

            - name: Run black
              run: |
                black control-plane/src/ control-plane/tests/ --check --diff

            - name: Run pylint
              run: pylint control-plane/src/ control-plane/tests/

    control-plane-test:
        runs-on: ubuntu-latest
        needs: control-plane-quality
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r control-plane/requirements.txt

            - name: Run tests
              run: pytest control-plane/tests/
